
- name: Ensure group "sshusers" exists
  ansible.builtin.group:
    name: sshusers
    state: present
  become: yes

- name: Create new user
  ansible.builtin.user:
    name: "{{ username }}"
    create_home: yes
    groups: sshusers
  become: yes

- name: Aloow SSH
  ansible.builtin.template:
    src: templates/allowusers.conf.j2
    dest: /etc/ssh/sshd_config.d/aloow_ssh_{{ username }}.conf
  become: yes